### ISSUE TITLE
cimi会出现问题吗？

### ISSUE THREAD

**Issue by fengxinhhh** [zzall/visualization-mock-server#1]
用cimi会出现什么问题吗，之前有同学走到1/3step就进行不下去了，今天改了一下代码。

**Comment by zzall** [comment]
我用着还好，目前没发现啥问题😄

**Comment by zzall** [comment]
> 用cimi会出现什么问题吗，之前有同学走到1/3step就进行不下去了，今天改了一下代码。

哦哦，这个是因为我那个run的代码注释了吧，我看你已经修复了。。
